version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: carluka/task-flow-backend:latest
    restart: always
    env_file: .env
    depends_on:
      - mysql
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    ports:
      - "8000:80"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: carluka/task-flow-frontend:latest
    restart: always
    depends_on:
      - api
    ports:
      - "3000:80"

volumes:
  mysql-data:
